export const fourCBridalJapaneseLuxuryTypographyProfile = {
  metadata: {
    id: '4c-bridal-japanese-luxury',
    name: '4C Bridal Japanese Luxury Typography',
    sourceName: '4℃ BRIDAL',
    purpose: 'Reference typography profile for Japanese bridal luxury rhythm, serif hierarchy, and restrained section spacing.',
    createdFor: 'DIAMOND SYMPHONY Astro',
  },
  sourceUrl: 'https://4-bridal.jp/',
  auditedAt: '2026-07-19',
  version: '0.1.0',
  viewportData: [
    { width: 1440, height: 1000, notes: 'Large desktop audit viewport.' },
    { width: 1280, height: 900, notes: 'Desktop audit viewport.' },
    { width: 1024, height: 900, notes: 'Small desktop/tablet landscape audit viewport.' },
    { width: 768, height: 1024, notes: 'Tablet portrait audit viewport.' },
    { width: 390, height: 844, notes: 'Mobile audit viewport.' },
    { width: 375, height: 812, notes: 'Small mobile audit viewport.' },
  ],
  referenceRoles: {
    logoH1: {
      selectorSample: 'h1.logo',
      semanticPurpose: 'Brand identity and page-level SEO anchor.',
      fontFamily: '"Zen Old Mincho", serif',
      fontCategory: 'serif',
      desktop: { fontSize: '24px', fontWeight: 500, lineHeight: '28.8px', letterSpacing: '0.64px' },
      dsMapping: 'hidden page title / brand display only',
    },
    largeSectionTitle: {
      selectorSample: 'h3.lv3.en',
      semanticPurpose: 'Primary homepage section title with English title and Japanese label.',
      fontFamily: '"EB Garamond", serif',
      fontCategory: 'editorial-serif',
      desktop: { fontSize: '46px', fontWeight: 500, lineHeight: '69px', letterSpacing: '3.68px' },
      color: 'rgb(54, 53, 61)',
      textAlign: 'center',
      dsMapping: 'section-title',
    },
    compactOverlayTitle: {
      selectorSample: 'h3.lv3.en.solid',
      semanticPurpose: 'Compact title over darker feature/service panels.',
      fontFamily: '"EB Garamond", serif',
      fontCategory: 'editorial-serif',
      desktop: { fontSize: '15px', fontWeight: 500, lineHeight: '22.5px', letterSpacing: '1.2px' },
      color: 'rgb(255, 255, 255)',
      textAlign: 'center',
      dsMapping: 'heading-secondary | group-title',
    },
    campaignTitle: {
      selectorSample: 'p.ttl',
      semanticPurpose: 'Campaign/card title.',
      fontFamily: '"Zen Old Mincho", serif',
      fontCategory: 'serif',
      desktop: { fontSize: '20px', fontWeight: 500, lineHeight: '30px', letterSpacing: '1.6px' },
      mobile: { fontSize: '16px', fontWeight: 500, lineHeight: '24px', letterSpacing: '1.28px' },
      dsMapping: 'card-title | heading-secondary',
    },
    dateCaption: {
      selectorSample: '.text._s',
      semanticPurpose: 'Date, campaign range, or compact supporting metadata.',
      fontFamily: '"Zen Old Mincho", serif',
      fontCategory: 'serif',
      desktop: { fontSize: '15px', fontWeight: 500, lineHeight: '22.5px', letterSpacing: '0.64px' },
      mobile: { fontSize: '14px', fontWeight: 500, lineHeight: '21px', letterSpacing: '0.64px' },
      dsMapping: 'caption',
    },
    supportBody: {
      selectorSample: '.text._ss',
      semanticPurpose: 'Small card description or support text.',
      fontFamily: '"Zen Old Mincho", serif',
      fontCategory: 'serif',
      desktop: { fontSize: '13px', fontWeight: 500, lineHeight: '20.8px', letterSpacing: '0.64px' },
      mobile: { fontSize: '13px', fontWeight: 500, lineHeight: '20.8px', letterSpacing: '0.64px' },
      dsMapping: 'body-secondary',
    },
    navigation: {
      selectorSample: 'header a, .header-top-info',
      semanticPurpose: 'Navigation and brand utility text.',
      fontFamily: '"Zen Old Mincho", serif',
      fontCategory: 'serif',
      desktop: { fontSize: '12px-16px', fontWeight: '500-600', lineHeight: '18px-24px', letterSpacing: '0.64px' },
      dsMapping: 'navigation | label',
    },
    footerUtility: {
      selectorSample: 'footer a, footer p',
      semanticPurpose: 'Footer links, reservation, legal, utility titles.',
      fontFamily: '"Zen Old Mincho", serif / "EB Garamond", serif',
      fontCategory: 'serif',
      desktop: { fontSize: '13px-14px', fontWeight: '600-700', lineHeight: '16.8px-21px', letterSpacing: '0-1.04px' },
      dsMapping: 'footer-link | button | caption',
    },
  },
  referenceScale: {
    displaySectionTitle: { min: 40, max: 46, preferred: 46, unit: 'px' },
    supportingPanelTitle: { min: 15, max: 24, preferred: 15, unit: 'px' },
    campaignTitle: { desktop: 20, mobile: 16, unit: 'px' },
    bodySecondary: { desktop: 13, mobile: 13, unit: 'px' },
    captionDate: { desktop: 15, mobile: 14, unit: 'px' },
    navigation: { min: 12, max: 16, unit: 'px' },
  },
  fontRelationships: {
    reference: {
      mainJapaneseSerif: '"Zen Old Mincho", serif',
      englishEditorialSerif: '"EB Garamond", serif',
    },
    dsTranslation: {
      editorialSerif: 'Use DS --font-editorial-serif for hero, section titles, editorial statements.',
      functionalSans: 'Keep DS --font-functional-sans for body, product browsing, buttons, and navigation.',
      warning: 'Do not globally change DS body/navigation to serif without a separate user request.',
    },
  },
  lineHeightScale: {
    display: 1.5,
    title: 1.45,
    campaignTitle: 1.5,
    bodySecondary: 1.6,
    navigation: 1.5,
    footerUtility: 1.2,
  },
  letterSpacingScale: {
    largeEnglishTitle: '0.08em',
    campaignTitle: '0.08em',
    bodySecondary: '0.049em',
    navigation: '0.04em',
    copyrightEnglish: '0.08em',
  },
  colorScale: {
    textPrimary: 'rgb(17, 17, 17)',
    textSoftPrimary: 'rgb(54, 53, 61)',
    textInverse: 'rgb(255, 255, 255)',
    ctaAccent: 'rgb(0, 44, 110)',
  },
  contentWidthRules: {
    campaignCardDesktop: '302px observed at 1440 viewport',
    campaignCardMobile: '154px-161px observed at 375-390 viewport within carousel layout',
    sectionTitleContainer: 'large centered section titles around 941px container on desktop',
    dsTranslation: 'Use DS content containers; apply reference as rhythm, not fixed widths.',
  },
  headingPatterns: {
    patternA: {
      name: 'English Serif Title + Japanese/Local Label',
      referenceExample: 'Brandブランドから探す',
      dsUse: 'English section label or title paired with Chinese section title, with DS hierarchy.',
    },
    patternB: {
      name: 'Compact Overlay Section Title',
      referenceExample: 'SERVICEサービス',
      dsUse: 'Featured panels, dark sections, service/consultation modules.',
    },
    patternC: {
      name: 'Campaign Card Title + Date + Description',
      referenceExample: 'Campaign title, date range, small description.',
      dsUse: 'News, knowledge cards, featured promotion cards.',
    },
  },
  spacingRelationships: {
    largeSectionTitleToContent: '40px observed margin-bottom',
    campaignTitleToDate: 'about 10px',
    footerUtilityTitleToList: '12px-15px',
    dsTranslation: 'Prefer consistent spacing tokens over increasing font sizes.',
  },
  responsiveRules: {
    titleReduction: 'Campaign titles reduce from 20px desktop to 16px mobile.',
    captionReduction: 'Date caption reduces from 15px desktop to 14px mobile.',
    lineHeightPreservation: 'Small text keeps generous line-height around 1.5-1.6.',
    dsTranslation: 'Protect mobile hierarchy with explicit title/body/caption roles.',
  },
  interactionRules: {
    hover: 'Text hover remains subtle; major movement is image/link treatment.',
    sliderPagination: 'Accessible button text may be visually hidden, but controls must remain perceivable.',
    focus: 'DS must preserve visible focus states.',
  },
  translationRules: {
    sectionTitle: 'Map to DS Section Title, not raw h3.lv3.en.',
    campaignTitle: 'Map to DS Card Title or Heading Secondary depending on section strength.',
    body: 'Map to DS Body Secondary for compact card descriptions.',
    navigation: 'Map to DS Navigation but keep DS sans unless applying a specific serif navigation theme.',
  },
  forbiddenCopyRules: [
    'Do not copy 4℃ BRIDAL logo styling into DS content.',
    'Do not copy Japanese campaign copy, campaign dates, or promotions.',
    'Do not copy reference imagery or layout assets.',
    'Do not globally replace DS body text with serif.',
    'Do not apply 46px section titles directly to all DS sections.',
  ],
} as const;

export default fourCBridalJapaneseLuxuryTypographyProfile;
